### ISSUE TITLE
Alternative library?

### ISSUE THREAD

**Issue by loganvolkers** [wspringer/barhandles#2]
It looks like this library hasn't been super well maintained and remains a proof of concept (correct me if I'm wrong).

The question for the maintainer and the community is: Has anyone found a better maintained alternative?

**Comment by wspringer** [comment]
Hi Logan: it was actually in use, perhaps surprisingly. There is no sensible alternative, and that's partly because of the structure of handlebars expressions, making it in some cases impossible to state anything at all about the expectations it has on the data it expects. Still, it has been helpful in our case.
